platform :ios, '8.0'

target 'NetJoyMachine' do

pod 'AFNetworking'

pod 'SDWebImage'

pod 'SDWebImage/GIF'

pod 'MJExtension'

pod 'IQKeyboardManager'

pod 'SVProgressHUD'

pod 'MJRefresh’

pod 'SDAutoLayout’

pod 'FMDB'

pod 'YYCache'

#pod 'SDCycleScrollView'

pod 'pop'

#pod 'WechatOpenSDK'

# U-Share SDK UI模块（分享面板，建议添加）
pod ‘UMengUShare/UI’

# 集成微信(精简版0.2M)
pod ‘UMengUShare/Social/ReducedWeChat'

pod 'JPush', '3.0.2'

pod 'CocoaAsyncSocket'

pod 'BRPickerView','~> 1.1.0'

end
